os: Visual Studio 2015
configuration:
  - Release
before_build:
  - cmake -G "Visual Studio 14 2015" src/
artifacts:
  - path: build\Release\xbash.exe
deploy:
  - provider: GitHub
    release: master-builds
    description: 'Automatic builds from the master branch'
    auth_token:
      secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
    artifact: /.*exe/
    draft: false
    prerelease: true
    on:
      branch: master
  - provider: GitHub
    release: xbash-$(APPVEYOR_REPO_TAG_NAME)
    description: 'Release'
    auth_token:
      secure: NMy2KE3EpZTjverxNzEAoBnlV+7VLGvwy3e1WEIrliFy3R1oxuT+AgGUDcRwv9y/
    artifact: /.*exe/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
